import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl">This is home page</h1>

        <Link href="/signup">
          <a>Sign up if you're new</a>
        </Link>
        <Link href="/login">
          <a>Or just Log in big fella</a>
        </Link>
      </main>

      <footer></footer>
    </div>
  );
}
